name: "Release"

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Should this push create a release?"
        required: true
        default: "false"
        type: boolean

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.create_release == 'true' }}
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2023.10.2
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Update devcontainer-feature.json version
        run: |
          jq --arg new_version "${{ steps.version.outputs.version }}" '.version = $new_version' src/base/devcontainer-feature.json > src/base/devcontainer-feature.json.tmp && mv src/base/devcontainer-feature.json.tmp src/base/devcontainer-feature.json

      - name: Release
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}